name: CI

on:
  push:
    branches:
      - JSL
  pull_request:
    branches:
      - JSL

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify your Python version here

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Adjust as per your project setup

    - name: Build and Test
      run: |
        # Add your build commands here
        # For example:
        python setup.py install
        pytest --cov=your_package_name --cov-report=xml

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage.xml
        flags: unittests
