name: Tests

on:
  push:
    branches:
      - JSL
  pull_request:
    branches:
      - JSL

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify your Python version here

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Adjust as per your project setup

    - name: Run tests
      run: |
        pytest

    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      with:
        name: Test Results
        path: test-results.xml
