name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install tox
      run: pip install tox

    - name: Run tests with tox
      run: tox

    - name: Generate coverage report
      run: |
        pip install coverage
        coverage run -m pytest
        coverage xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: CODECOV_TOKEN=f7652b06-0b26-4d33-b77f-79e74d237308
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
